### ISSUE TITLE
How to reduce the parameters of the bigvgan model

### ISSUE THREAD

**Issue by 980202006** [sh-lee-prml/BigVGAN#12]
Great work!This code reproduce the effect of the original paper very well.It has lots of parameters, which make it hard to train with acoustic model.Can you give me some advices of how to reduce the parameters of the bigvgan model?

**Comment by sh-lee-prml** [comment]
Thanks for your interest

I just trained the bigvgan-base model, which has a little more parameter (due to learnable alpha parameters).

So, if the acoustic model you mentioned is TTS model, it's almost same with original VITS.

If you have a problem with your own dataset, I recommend removing the long speech data over 8 ~ 10s. 

In my experiment, using the VCTK data under the 400 spectrograme frame is also enough to train the tts model.

**Comment by 980202006** [comment]
Hi,I noticed that you used rand_slice_segments before  the posterior z  enters the vocoder in the model_vits_with_bigvgan.py.How many steps did the model take to convege?Can you provide some samples about the vits_bigvgan model?

**Comment by 980202006** [comment]
Thank you for your reply.!

**Comment by 980202006** [comment]
Hi, have you compared the effect of using rand_slice_segments and not using rand_slice_segments?

**Comment by sh-lee-prml** [comment]
> Hi, have you compared the effect of using rand_slice_segments and not using rand_slice_segments?

Due to the GPU memory limitation, you should train your model by with rand_slice_segments. We use the same size of it from the HiFi-GAN 8192 (256 hop size * 32 segments)

**Comment by 980202006** [comment]
Thank you for your reply!
